### ISSUE TITLE
Interval::difference method is probably invalid

### ISSUE THREAD

**Issue by K0nias** [Achse/php-math-interval#19]
One more thing. This test is invalid https://github.com/Achse/php-math-interval/blob/master/src/Interval.php#L341 right? Since Interval::intersection method return another instance of Interval every time.

**Comment by Achse** [comment]
Yes it is. Intersection no longer returns null when there is no intersection. It's relic of previous version.

**Comment by K0nias** [comment]
Yeah I have prepared another PR :)
